name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - name: Use node 16.11
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:unit

